# Generated by Django 3.1.3 on 2021-01-05 11:14

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('reminder', models.DateTimeField(blank=True, null=True)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18)),
                ('image', models.ImageField(blank=True, null=True, upload_to='notes/')),
                ('is_archived', models.BooleanField(blank=True, default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_trashed', models.BooleanField(default=False)),
            ],
        ),
    ]
