# Generated by Django 3.1.3 on 2020-12-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfundooNotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
