# Generated by Django 3.1.3 on 2020-12-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Label', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
